# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 477b100c38e5ab325d1b37cf3957189d55bf8d22792b9e1caa61364de047cea7096d5aae076c640d7f44ed36da1f7e1b0314e3c2e6c00158b12d165c59776948

test:
  secret_key_base: 26d3d84e62633e4e437f9e9ad7c4bb2a58b7d818879e7718fcfdbf5a57b27900fd39d4d2eaa1e714b696fcbf81e6afb83188983a5fb7bb8f9df1f7ccfd589847

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
